const ICON_SIZE_MARKER = [52, 52];
const ICON_ANCHOR_MARKER = [26, 52];
const MINIMAL_NUMBER_BALUN = 10;
const ICON_SIZE_BALUN = [40, 40];
const ICON_ANCHOR_BALUN = [20, 40];
const MARKER_LAN_LNG = [35.68172, 139.75392];
const TITLEADS_MIN_LENGTH = 30;
const TITLEADS_MAX_LENGTH = 100;
const NUMBER_GUESTS_VALUE = [0, 1, 2, 3];
const MAP_SIZE = 10;
const COUNT_MIN_PLACEHOLDER = {
  select: 0,
  bungalow: 0,
  flat: 1000,
  hotel: 3000,
  house: 5000,
  palace: 10000,
};
const OFFER_PRICE = {
  lowPrice: 10000,
  highPrice: 50000,
};

export{MINIMAL_NUMBER_BALUN, ICON_SIZE_BALUN, ICON_ANCHOR_BALUN, MARKER_LAN_LNG, TITLEADS_MIN_LENGTH, TITLEADS_MAX_LENGTH, NUMBER_GUESTS_VALUE, COUNT_MIN_PLACEHOLDER, MAP_SIZE, ICON_SIZE_MARKER, ICON_ANCHOR_MARKER, OFFER_PRICE};

